### ISSUE TITLE
Write README

### ISSUE THREAD

**Issue by Mast3rwaf1z** [f-klubben/fnix#1]
thinking something like this:
## dev env
* recommended to test in a VM
  * maybe even add how to replicate the system
* clone to /etc/nixos
## new services
* add in /etc/nixos/services
* custom services example

some diagram of the system architecture could also be nice, like where the http server would have endpoints at, or which services are at which ports

**Comment by TobiasSN** [comment]
I think it would be most useful to start writing the README after we've started developing the actual configuration, so we have an idea of what sort of documentation is actually useful, and concretely what to write.

Good starting outline though!

**Comment by Mast3rwaf1z** [comment]
What I meant was that I think we should document the environment setup while setting up the initial configuration, so working on this issue while writing the config

**Comment by Mast3rwaf1z** [comment]
#8 closed this
