### ISSUE TITLE
Change fnix to fix

### ISSUE THREAD

**Issue by miniJmo** [f-klubben/fnix#19]

**Comment by krestenlaust** [comment]
I think this will have a negative effect on the project going forward. I will not expand upon this

**Comment by TobiasSN** [comment]
"Fnix" is more fun to pronounce

**Comment by soupglasses** [comment]
Further this will instantly get confused by the English word for `fix`, one of the most common prefixes to all commits, besides `feat`.

**Comment by krestenlaust** [comment]
Plz Fnix

**Comment by soupglasses** [comment]
No, wont-fnix.
